[profile.default]
src = "src"
out = "foundry-out"
libs = ["node_modules","lib"]
ffi = true
solc_version = "0.8.26"
evm_version = "cancun"
remappings = [
    "forge-std/=lib/forge-std/src",
    "solmate/=lib/solmate",
    "foundry-devops/=lib/foundry-devops/src/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@reactive-network/=lib/reactive-smart-contract-demos/lib/reactive-lib/src/"
]


[rpc_endpoints]
sepolia = "https://g.w.lavanet.xyz:443/gateway/sep1/rpc-http/0e1cfb566bd2ce33c7cb707c85397e07"
reactive-testnet="https://lasna-rpc.rnk.dev/"


[etherscan]

sepolia = {key = "${ETHERSCAN_API_KEY}"}


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
