// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.8.0;


//NOTE :THE BEAUTY OF THE REACTIVE NETWROK IS TO BE ABLE TO DO CROSS CHAIN ARBITRAGE
// ACROSS POOL MANAGER ON DIFFERENT CHAINS, BECAUSE UNI-CHAIN ARBITRAGE CAN BE DONE USEING BEFORE
// INITIALIZE ON A HOOK
// THIUS WE NEED TO DO DIFFERENCTIAL TESTING TO PROVE THAT UNDER THE SAME CONDITIONS, BOTH
// APPROACHES LEAD TO THE SAME STATE (AFTER TRADE)